// packages/react/src/index.ts
export { KLineChartWC, type KLineChartWCProps, type KLineChartWCHandle } from './KLineChartWC'

export type { SemanticChartConfig } from '@363045841yyt/klinechart-core/semantic'

import {
  createElement,
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from 'react'
import type { CSSProperties, ForwardedRef, FC, RefObject } from 'react'
import type {
  ChartController,
  ChartControllerFactory,
  ChartMountOptions,
  ChartViewport,
  IndicatorInstance,
  InteractionSnapshot,
  KLineData,
  SymbolSpec,
  DataFetcher,
  DrawingControllerCallbacks,
} from '@363045841yyt/klinechart-core'

export type {
  ChartController,
  ChartMountOptions,
  ChartViewport,
  SymbolSpec,
  DataFetcher,
} from '@363045841yyt/klinechart-core'

let chartFactory: ChartControllerFactory | null = null

export function __setChartFactory(factory: ChartControllerFactory | null): void {
  chartFactory = factory
}

function resolveFactory(): ChartControllerFactory {
  if (chartFactory === null) {
    throw new Error(
      '[@363045841yyt/klinechart-react] No ChartControllerFactory registered. ' +
        'Call __setChartFactory(factory) before mounting, or import the ' +
        'production factory from @363045841yyt/klinechart-core/controllers.',
    )
  }
  return chartFactory
}

export function createChart(opts: ChartMountOptions): ChartController | Promise<ChartController> {
  if (opts === null || opts === undefined) {
    throw new Error('[@363045841yyt/klinechart-react] createChart: opts is required')
  }
  if (opts.container === null || opts.container === undefined) {
    throw new Error(
      '[@363045841yyt/klinechart-react] createChart: opts.container must be a non-null HTMLElement',
    )
  }
  const factory = resolveFactory()
  return factory(opts)
}

export function useChart(
  ref: RefObject<HTMLElement | null>,
  opts: Omit<ChartMountOptions, 'container'>,
): ChartController | null {
  const [controller, setController] = useState<ChartController | null>(null)
  const controllerRef = useRef<ChartController | null>(null)
  const optsRef = useRef(opts)
  optsRef.current = opts

  useEffect(() => {
    const container = ref.current
    if (container === null || container === undefined) {
      return
    }
    let mounted = true
    const created = createChart({
      ...optsRef.current,
      container,
    })
    const applyController = (next: ChartController) => {
      if (!mounted) {
        next.dispose()
        return
      }
      controllerRef.current = next
      setController(next)
    }

    if (typeof (created as Promise<ChartController>).then === 'function') {
      ;(created as Promise<ChartController>).then(applyController)
    } else {
      applyController(created as ChartController)
    }
    return () => {
      mounted = false
      controllerRef.current?.dispose()
      controllerRef.current = null
      setController(null)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ref])

  return controller
}

type IndicatorsView = {
  indicators: ReadonlyArray<IndicatorInstance>
  add: ChartController['addIndicator']
  remove: ChartController['removeIndicator']
  updateParams: ChartController['updateIndicatorParams']
}

export function useIndicators(controller: ChartController): IndicatorsView {
  const indicators = controller.indicators

  const subscribe = useCallback((cb: () => void) => indicators.subscribe(cb), [indicators])

  const { getSnapshot } = useMemo(() => {
    let cached: IndicatorsView | null = null
    return {
      getSnapshot: (): IndicatorsView => {
        const next = indicators()
        if (cached !== null && cached.indicators === next) return cached
        cached = {
          indicators: next,
          add: controller.addIndicator.bind(controller),
          remove: controller.removeIndicator.bind(controller),
          updateParams: controller.updateIndicatorParams.bind(controller),
        }
        return cached
      },
    }
  }, [indicators, controller])

  const getServerSnapshot = getSnapshot

  const snapshot = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot)

  return snapshot
}

export function useInteractionState(controller: ChartController): InteractionSnapshot {
  const store = controller.interactionState

  const subscribe = useCallback((cb: () => void) => store.subscribe(cb), [store])

  const getSnapshot = useCallback(() => store(), [store])

  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
}

export function usePaneRatios(controller: ChartController): Readonly<Record<string, number>> {
  const store = controller.paneRatios

  const subscribe = useCallback((cb: () => void) => store.subscribe(cb), [store])

  const getSnapshot = useCallback(() => store(), [store])

  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
}

export function useViewport(controller: ChartController): ChartViewport {
  const store = controller.viewport

  const subscribe = useCallback((cb: () => void) => store.subscribe(cb), [store])

  const getSnapshot = useCallback(() => store(), [store])

  return useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
}

export interface KLineChartProps {
  data: ChartMountOptions['data']
  symbols?: ChartMountOptions['symbols']
  dataFetcher?: ChartMountOptions['dataFetcher']
  initialZoomLevel?: number
  theme?: 'light' | 'dark'
  zoomLevels?: number
  className?: string
  style?: CSSProperties
}

export interface KLineChartHandle {
  getController: () => ChartController | null
  handlePointerEvent: (e: PointerEvent, drawingController?: DrawingControllerCallbacks) => boolean
  handleWheelEvent: (e: WheelEvent) => void
  handleScrollEvent: () => void
  zoomToLevel: (level: number, anchorX?: number) => void
  zoomIn: (anchorX?: number) => void
  zoomOut: (anchorX?: number) => void
  addIndicator: (
    definitionId: string,
    role: 'main' | 'sub',
    params?: Record<string, unknown>,
  ) => string | null
  removeIndicator: (instanceId: string) => boolean
  setTheme: (theme: 'light' | 'dark') => void
  setData: (next: ReadonlyArray<KLineData>) => void
  setSymbols: (next: ReadonlyArray<SymbolSpec>) => void
  setDataFetcher: (fetcher: DataFetcher | null) => void
}

export const KLineChart = forwardRef<KLineChartHandle, KLineChartProps>(function KLineChart(
  { data, symbols, dataFetcher, initialZoomLevel, theme, zoomLevels, className, style },
  ref: ForwardedRef<KLineChartHandle>,
) {
  const divRef = useRef<HTMLDivElement | null>(null)
  const controllerRef = useRef<ChartController | null>(null)

  useEffect(() => {
    const container = divRef.current
    if (container === null) return
    let mounted = true
    const created = createChart({
      container,
      data,
      symbols,
      dataFetcher,
      initialZoomLevel,
      zoomLevels,
      theme,
    })
    const applyController = (next: ChartController) => {
      if (!mounted) {
        next.dispose()
        return
      }
      controllerRef.current = next
    }
    if (typeof (created as Promise<ChartController>).then === 'function') {
      ;(created as Promise<ChartController>).then(applyController)
    } else {
      applyController(created as ChartController)
    }
    return () => {
      mounted = false
      controllerRef.current?.dispose()
      controllerRef.current = null
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (data !== undefined) {
      controllerRef.current?.setData(data)
    }
  }, [data])

  useEffect(() => {
    if (theme !== undefined) {
      controllerRef.current?.setTheme(theme)
    }
  }, [theme])

  useImperativeHandle(
    ref,
    (): KLineChartHandle => ({
      getController: (): ChartController | null => controllerRef.current,
      handlePointerEvent: (e, dc) => controllerRef.current?.handlePointerEvent(e, dc) ?? false,
      handleWheelEvent: (e) => controllerRef.current?.handleWheelEvent(e),
      handleScrollEvent: () => controllerRef.current?.handleScrollEvent(),
      zoomToLevel: (level, anchorX) => controllerRef.current?.zoomToLevel(level, anchorX),
      zoomIn: (anchorX) => controllerRef.current?.zoomIn(anchorX),
      zoomOut: (anchorX) => controllerRef.current?.zoomOut(anchorX),
      addIndicator: (id, role, params) =>
        controllerRef.current?.addIndicator(id, role, params) ?? null,
      removeIndicator: (id) => controllerRef.current?.removeIndicator(id) ?? false,
      setTheme: (t) => controllerRef.current?.setTheme(t),
      setData: (next) => controllerRef.current?.setData(next),
      setSymbols: (next) => controllerRef.current?.setSymbols(next),
      setDataFetcher: (fetcher) => controllerRef.current?.setDataFetcher(fetcher),
    }),
    [],
  )

  return createElement('div', { ref: divRef, className, style })
})

import { createChartController } from '@363045841yyt/klinechart-core'
__setChartFactory(createChartController)

// packages/angular/src/index.ts
/**
 * @363045841yyt/klinechart-angular —public API surface.
 *
 * Standalone Angular 17+/18+/19+ bindings for @363045841yyt/klinechart-core.
 * No NgModule. Bridges the core push-based signal layer into Angular's
 * own `signal()` so OnPush components refresh when controllers mutate state.
 */

import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  type ElementRef,
  InjectionToken,
  Input,
  type OnChanges,
  type OnDestroy,
  PLATFORM_ID,
  type Provider,
  type Signal as NgSignal,
  type SimpleChanges,
  ViewChild,
  inject,
  signal,
} from '@angular/core'
import { isPlatformBrowser } from '@angular/common'
import type {
  ChartController,
  ChartControllerFactory,
  ChartMountOptions,
  ChartViewport,
  DataFetcher,
  DrawingControllerCallbacks,
  IndicatorInstance,
  InteractionSnapshot,
  KLineData,
  Signal as CoreSignal,
  SymbolSpec,
} from '@363045841yyt/klinechart-core'
import { createChartController } from '@363045841yyt/klinechart-core'

export type {
  ChartController,
  ChartMountOptions,
  ChartControllerFactory,
  DataFetcher,
  SymbolSpec,
} from '@363045841yyt/klinechart-core'

// ---------------------------------------------------------------------------
// DI tokens
// ---------------------------------------------------------------------------

/** Globally-configured default theme. Component @Input wins per-instance. */
export const KLINE_CHART_THEME = new InjectionToken<'light' | 'dark'>('KLINE_CHART_THEME', {
  providedIn: 'root',
  factory: () => 'light' as const,
})

/**
 * Factory used by `<kline-chart>` to produce a controller. Defaults to the
 * production `createChartController` from `@363045841yyt/klinechart-core`, so
 * consumers don't need to register it manually. Override per-application
 * via `provideKLineChart({ factory })` —useful for tests that inject a
 * mock factory.
 */
export const KLINE_CHART_FACTORY = new InjectionToken<ChartControllerFactory | null>(
  'KLINE_CHART_FACTORY',
  { providedIn: 'root', factory: (): ChartControllerFactory => createChartController },
)

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

export interface ProvideKLineChartOptions {
  theme?: 'light' | 'dark'
  factory?: ChartControllerFactory
}

/**
 * DI provider factory. Usage:
 *
 *   providers: [provideKLineChart({ theme: 'dark', factory: createChartController })]
 */
export function provideKLineChart(opts: ProvideKLineChartOptions = {}): Provider[] {
  const providers: Provider[] = []
  if (opts.theme !== undefined) {
    providers.push({ provide: KLINE_CHART_THEME, useValue: opts.theme })
  }
  if (opts.factory !== undefined) {
    providers.push({ provide: KLINE_CHART_FACTORY, useValue: opts.factory })
  }
  return providers
}

// ---------------------------------------------------------------------------
// Signal bridge: core Signal<T> -> Angular Signal<T>
// ---------------------------------------------------------------------------

/**
 * Wrap a core signal into an Angular readonly signal. Unsubscribes via
 * the supplied `DestroyRef` —or, if omitted, `inject(DestroyRef)` from
 * the surrounding injection context.
 */
export function coreSignalToAngular<T>(
  source: CoreSignal<T>,
  destroyRef?: DestroyRef,
): NgSignal<T> {
  const ng = signal<T>(source.peek())
  const unsubscribe = source.subscribe(() => {
    ng.set(source.peek())
  })
  const ref = destroyRef ?? inject(DestroyRef)
  ref.onDestroy(unsubscribe)
  return ng.asReadonly()
}

// ---------------------------------------------------------------------------
// createChart —imperative escape hatch
// ---------------------------------------------------------------------------

/**
 * Imperative escape hatch. Mirrors React/Vue.
 */
export async function createChart(
  opts: ChartMountOptions & { factory?: ChartControllerFactory },
): Promise<ChartController> {
  if (opts.container === null || opts.container === undefined) {
    throw new Error('createChart: container is required')
  }
  if (typeof opts.factory !== 'function') {
    throw new Error(
      'createChart: no ChartControllerFactory provided. Pass `factory` in opts or register one via provideKLineChart({ factory }).',
    )
  }
  const { factory, ...mountOpts } = opts
  return await factory(mountOpts)
}

// ---------------------------------------------------------------------------
// <kline-chart> standalone component
// ---------------------------------------------------------------------------

@Component({
  selector: 'kline-chart',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<div #container style="width:100%;height:100%;"></div>',
})
export class KLineChartComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() data: ReadonlyArray<KLineData> = []
  @Input() symbols: ReadonlyArray<SymbolSpec> | undefined = undefined
  @Input() dataFetcher: DataFetcher | undefined = undefined
  @Input() theme: 'light' | 'dark' | undefined = undefined
  @Input() initialZoomLevel: number | undefined = undefined
  @Input() zoomLevels: number | undefined = undefined

  @ViewChild('container', { static: true })
  container!: ElementRef<HTMLElement>

  // Private writable signals —only values change, never reassigned
  private _viewport = signal<ChartViewport | null>(null)
  private _interactionState = signal<InteractionSnapshot | null>(null)
  private _paneRatios = signal<Readonly<Record<string, number>> | null>(null)
  private _indicators = signal<ReadonlyArray<IndicatorInstance> | null>(null)

  /** Angular signals mirroring controller state —readonly wrappers, references never change. */
  readonly viewport = this._viewport.asReadonly()
  readonly interactionState = this._interactionState.asReadonly()
  readonly paneRatios = this._paneRatios.asReadonly()
  readonly indicators = this._indicators.asReadonly()

  /** Underlying core controller; null until ngAfterViewInit. */
  controller: ChartController | null = null

  private readonly platformId = inject(PLATFORM_ID)
  private readonly defaultTheme = inject(KLINE_CHART_THEME)
  private readonly factory = inject(KLINE_CHART_FACTORY)
  private readonly destroyRef = inject(DestroyRef)

  async ngAfterViewInit(): Promise<void> {
    if (!isPlatformBrowser(this.platformId)) return

    const containerEl = this.container?.nativeElement ?? null
    if (containerEl === null) return
    if (typeof this.factory !== 'function') {
      throw new Error(
        '<kline-chart>: no ChartControllerFactory registered. Add provideKLineChart({ factory }) at the application bootstrap.',
      )
    }

    const controller = await createChart({
      container: containerEl,
      data: this.data,
      symbols: this.symbols,
      dataFetcher: this.dataFetcher,
      initialZoomLevel: this.initialZoomLevel,
      zoomLevels: this.zoomLevels,
      theme: this.theme ?? this.defaultTheme,
      factory: this.factory,
    })
    this.controller = controller

    // Bridge viewport
    this._viewport.set(controller.viewport.peek())
    this.destroyRef.onDestroy(
      controller.viewport.subscribe(() => this._viewport.set(controller.viewport.peek())),
    )

    // Bridge interactionState
    this._interactionState.set(controller.interactionState.peek())
    this.destroyRef.onDestroy(
      controller.interactionState.subscribe(() =>
        this._interactionState.set(controller.interactionState.peek()),
      ),
    )

    // Bridge paneRatios
    this._paneRatios.set(controller.paneRatios.peek())
    this.destroyRef.onDestroy(
      controller.paneRatios.subscribe(() => this._paneRatios.set(controller.paneRatios.peek())),
    )

    // Bridge indicators
    this._indicators.set(controller.indicators.peek())
    this.destroyRef.onDestroy(
      controller.indicators.subscribe(() => this._indicators.set(controller.indicators.peek())),
    )
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data'] && !changes['data'].isFirstChange()) {
      this.controller?.setData(this.data)
    }
    if (changes['theme'] && !changes['theme'].isFirstChange()) {
      if (this.theme !== undefined) {
        this.controller?.setTheme(this.theme)
      }
    }
  }

  ngOnDestroy(): void {
    if (this.controller !== null) {
      try {
        this.controller.dispose()
      } finally {
        this.controller = null
      }
    }
  }

  // -------------------------------------------------------------------
  // Event handler passthroughs
  // -------------------------------------------------------------------

  handlePointerEvent(e: PointerEvent, drawingController?: DrawingControllerCallbacks): boolean {
    return this.controller?.handlePointerEvent(e, drawingController) ?? false
  }

  handleWheelEvent(e: WheelEvent): void {
    this.controller?.handleWheelEvent(e)
  }

  handleScrollEvent(): void {
    this.controller?.handleScrollEvent()
  }

  zoomToLevel(level: number, anchorX?: number): void {
    this.controller?.zoomToLevel(level, anchorX)
  }

  zoomIn(anchorX?: number): void {
    this.controller?.zoomIn(anchorX)
  }

  zoomOut(anchorX?: number): void {
    this.controller?.zoomOut(anchorX)
  }

  addIndicator(
    definitionId: string,
    role: 'main' | 'sub',
    params?: Record<string, unknown>,
  ): string | null {
    return this.controller?.addIndicator(definitionId, role, params) ?? null
  }

  removeIndicator(instanceId: string): boolean {
    return this.controller?.removeIndicator(instanceId) ?? false
  }

  setTheme(theme: 'light' | 'dark'): void {
    this.controller?.setTheme(theme)
  }

  setData(next: ReadonlyArray<KLineData>): void {
    this.controller?.setData(next)
  }

  setSymbols(next: ReadonlyArray<SymbolSpec>): void {
    this.controller?.setSymbols(next)
  }

  setDataFetcher(fetcher: DataFetcher | null): void {
    this.controller?.setDataFetcher(fetcher)
  }
}
